// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type LoginAttempt struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	CreatedAt string         `json:"created_at"`
	Success   int64          `json:"success"`
}

type User struct {
	ID                string `json:"id"`
	Role              string `json:"role"`
	Username          string `json:"username"`
	Email             string `json:"email"`
	Password          string `json:"password"`
	Status            string `json:"status"`
	PasswordUpdatedAt string `json:"password_updated_at"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type UserSession struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	Token          string `json:"token"`
	SessionData    string `json:"session_data"`
	CreatedAt      string `json:"created_at"`
	ExpiresAt      string `json:"expires_at"`
	LastAccessedAt string `json:"last_accessed_at"`
}

type UsersMetum struct {
	UserID    string `json:"user_id"`
	MetaKey   string `json:"meta_key"`
	MetaValue string `json:"meta_value"`
}
