// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package userQuery

import (
	"database/sql"
)

type LoginAttempt struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	CreatedAt string         `json:"created_at"`
	Success   int64          `json:"success"`
}

type User struct {
	ID                string         `json:"id"`
	Username          string         `json:"username"`
	Email             string         `json:"email"`
	Password          string         `json:"password"`
	PasswordUpdatedAt sql.NullString `json:"password_updated_at"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type UserRole struct {
	UserID string `json:"user_id"`
	RoleID int64  `json:"role_id"`
}

type UsersMetum struct {
	UserID    string `json:"user_id"`
	MetaKey   string `json:"meta_key"`
	MetaValue string `json:"meta_value"`
}
