// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package userQuery

import (
	"context"
)

type Querier interface {
	AddUserMeta(ctx context.Context, arg AddUserMetaParams) (UsersMetum, error)
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id string) error
	GetUser(ctx context.Context, id string) (GetUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserMeta(ctx context.Context, arg UpdateUserMetaParams) (UsersMetum, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UserRole, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UsersMetum, error)
	UserExists(ctx context.Context, id string) (bool, error)
}

var _ Querier = (*Queries)(nil)
